language: c

matrix:
  include:
  - os: linux
    dist: precise
  - os: linux
    dist: trusty
  - os: osx

install: true
cache:
  directories:
  - test/test_suite

script:
- ./build
- ./libbuild
- cd test
- ./download_suite
- ./build
- ./oppai_test
- LDFLAGS="-loppai" ./build -L..
- LD_LIBRARY_PATH=.. DYLD_LIBRARY_PATH=.. ./oppai_test
